name: streamy
version: 0.0.5
description: >
  An experimental client API generator for services described using Google's API
  discovery format (https://developers.google.com/discovery/v1/using#discovery-doc).
  The generator comes with templates that generate streaming API via dart:async's
  Stream object.
authors:
- Alex Rickabaugh <arick@google.com>
- Yegor Jbanov <yjbanov@google.com>
homepage: https://github.com/google/streamy-dart
environment:
  sdk: '>=0.8.1'
dependencies:
  args: any
  fixnum: ">=0.7.6"
  json: ">=0.8.5"
  mustache: ">=0.1.5"
  meta: any
  observe: any
  quiver: ">=0.11.0"
dev_dependencies:
  path: any
  unittest: any
  benchmark_harness: any
